[git]
# Only include commits since the last tag
tag_pattern = "v[0-9]*"
conventional_commits = true

[changelog]
# Where to output
output = "CHANGELOG.md"
# Sort commits by newest first
sort = "desc"

[template]
# Basic template (you can go fancier later)
tag = "## {{ version }}"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message }} ({{ commit.id | truncate(length=7) }})
{% endfor %}
{% endfor %}
"""

